config/routes.rb
Rails.application.routes.draw do
  resources :answer_questions
  resources :spells
  resources :question_answer
  resources :answer
  resources :question
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "static#home"
  get '/great_hall', to: "great_hall#index"
  get '/great_hall/gryffindor', to: "gryffindor#index"
  get '/great_hall/gryffindor/:id', to: "gryffindor#show"
  get '/great_hall/hufflepuff', to: "hufflepuff#index"
  get '/great_hall/hufflepuff/:id', to: "hufflepuff#show"
  get '/great_hall/ravenclaw', to: "ravenclaw#index"
  get '/great_hall/ravenclaw/:id', to: "ravenclaw#show"
  get '/great_hall/slytherin', to: "slytherin#index"
  get '/great_hall/slytherin/:id', to: "slytherin#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :answer_question
  has_many :questions, through: :answer_question
end

app/models/answer_question.rb
class AnswerQuestion < ApplicationRecord
  belongs_to :answer
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/great_hall.rb
class GreatHall < ApplicationRecord
  def self.get_spells(users, spells)
    indi_spells = []
    users.each do |user|
      if user.spells.exists?
        user.spells.each do |spell|
          indi_spells.push spell
        end
      end
    end
    indi_spells 
  end

  def self.get_indi_spells(user, spells)
    indi_spells = []
      if user.spells.exists?
        user.spells.each do |spell|
          indi_spells.push spell
        end
      end
    indi_spells
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answer_questions
  has_many :answers, through: :answer_questions

  def self.houses id, user
    house = [user.gryffindor, user.ravenclaw, user.hufflepuff, user.slytherin]
    result = house.each_with_index.max[1]
    puts result

    case result
    when 0
      "Gryffindor"
    when 1
      "Ravenclaw"
    when 2
      "Hufflepuff"
    when 3
      "Slytherin"
    end
  end
end

app/models/spell.rb
class Spell < ApplicationRecord
  # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :spells
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
  end

  def show
    @user = current_user
    @house = @user.house
  end

  def update
    redirect_to "/great_hall"
  end
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  before_action :authenticate_user!
  def index
    @questions = Question.all
  end

  def show
    id = params[:id]
    @question = Question.find id
    @user = current_user
    if @user.sorted
      redirect_to "/"
    end
    if id.to_i + 1 == 9
      @next = "/answer"
    else
      @next = "/question/#{@question.id + 1}"
    end
  end

  def update
    id = params[:id]
    user = current_user
    user.update_attribute(:gryffindor, question_params[:gryffindor].to_f + user.gryffindor)
    user.update_attribute(:ravenclaw, question_params[:ravenclaw].to_f + user.ravenclaw)
    user.update_attribute(:hufflepuff, question_params[:hufflepuff].to_f + user.hufflepuff)
    user.update_attribute(:slytherin, question_params[:slytherin].to_f + user.slytherin)

    if id.to_i + 1 == 9
      result = Question.houses(id, user)
      user.update_attribute(:house, result)
      user.update_attribute(:sorted, true)
      redirect_to "/answer"
    else
      redirect_to "/question/#{id.to_i + 1}"
    end
  end

   private
    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:gryffindor, :ravenclaw, :hufflepuff, :slytherin)
    end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy]

  def index
    @spells = Spell.all
  end

  def show
    @spell = Spell.find(params[:id])
  end

  def new
    @spell = Spell.new
  end

  def edit
  end

  def create
   
    @user = current_user
    @new_spell = Spell.create(spell_params)
    @new_spell.user_id = @user.id
    @new_spell.save
    redirect_to "/great_hall/#{@user.house.downcase}"
  end

  def update
    @user = current_user
    @spell.update(spell_params)
    redirect_to "/great_hall/#{@user.house.downcase}"
  end

  def destroy
    @spell.destroy
    redirect_to request.referrer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spell_params
      params.require(:spell).permit(:name, :catagory, :description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController\

  def home
    @users = User.all
    @user = current_user
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/answer_questions_helper.rb
module AnswerQuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/great_hall_helper.rb
module GreatHallHelper
end

app/helpers/gryffindor_helper.rb
module GryffindorHelper
end

app/helpers/hufflepuff_helper.rb
module HufflepuffHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/ravenclaw_helper.rb
module RavenclawHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/slytherin_helper.rb
module SlytherinHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/answer/index.html.erb
<section>
  <% if @user.house == "Gryffindor" %>
    <div class="banner red">
      <%= image_tag "gryffindor.png", class: "house-badge" %>
    </div>
  <% end %>

  <% if @user.house == "Hufflepuff" %>
  <div class="banner yellow">
    <%= image_tag "hufflepuff.png", class: "house-badge" %>
  </div>
  <% end %>

  <div class="scroll">
    <%= image_tag "scroll.png", class: "img-responsive scroll-img" %>

    <h1>Congratulations!</h1>
    <h3>You have been sorted into</h3>
    <h2><%= @user.house %></h2>

    <%= link_to "Take me to the Great Hall!", "/great_hall", id: "hall-link" %> 

  </div>

  <% if @user.house == "Ravenclaw" %>
    <div class="banner blue">
      <%= image_tag "ravenclaw.png", class: "house-badge" %>
    </div>
  <% end %>

  <% if @user.house == "Slytherin" %>
    <div class="banner green">
      <%= image_tag "slytherin.png", class: "house-badge" %>
    </div>
  <% end %>

</section>

app/views/question/index.html.erb
<section>
  <div class="banner red">
    <%= image_tag "gryffindor.png", class: "house-badge" %>
  </div>
  <div class="banner yellow">
    <%= image_tag "hufflepuff.png", class: "house-badge" %>
  </div>
  <div class="scroll-register">
    <%= image_tag "scrolllarge.png", class: "img-responsive scroll-img" %>

    <h1>Questions</h1>
    <div id="begin">
      <%= link_to 'Begin', "/question/1" %>
    </div>

  </div>
  <div class="banner blue">
    <%= image_tag "ravenclaw.png", class: "house-badge" %>
  </div>
  <div class="banner green">
    <%= image_tag "slytherin.png", class: "house-badge" %>
  </div>

</section>

app/views/question/show.html.erb
<section>
  <div class="banner red">
    <%= image_tag "gryffindor.png", class: "house-badge" %>
  </div>
  <div class="banner yellow">
    <%= image_tag "hufflepuff.png", class: "house-badge" %>
  </div>
  <div class="scroll-question">
    <%= image_tag "scrolllarge.png", class: "img-responsive scroll-img" %>

    <h2><%= @question.text %></h2>

    <div class="answers">
      <% @question.answers.each do |answer| %>

        <%= form_with(model: @question) do |f| %>
        <%= f.hidden_field :tag, value: answer.tag%>
        <%= f.hidden_field :gryffindor, value: answer.gryffindor%>
        <%= f.hidden_field :ravenclaw, value: answer.ravenclaw%>
        <%= f.hidden_field :hufflepuff, value: answer.hufflepuff%>
        <%= f.hidden_field :slytherin, value: answer.slytherin%>

        <div class="field">
          <%= f.submit value: answer.tag %>
        </div>
        <% end %>
      <% end %>
    </div>

  </div>
  <div class="banner blue">
    <%= image_tag "ravenclaw.png", class: "house-badge" %>
  </div>
  <div class="banner green">
    <%= image_tag "slytherin.png", class: "house-badge" %>
  </div>

</section>

app/views/spells/_form.html.erb
<%= form_for @spell do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.select :catagory, [['Charm', 'charm'],['Hex', 'hex'],['Jinx', 'jinx'],['Curse', 'curse'],['Transfiguration', 'transfiguration'],['Healing spell', 'healling spell'],['Counter-spell', 'counter-spell']]%>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Submit spell" %>
  </div>

<% end %>

app/views/spells/edit.html.erb
<div id="spell-body">

  <div id="scroll-spells">
    <%= image_tag "scroll.png", id: "spell-scroll", class: "img-responsive" %>

    <h1>Edit Spell</h1>
    <%= render 'form', spell: @spell %>

    <%= link_to 'Back', spells_path %>

  </div>

</div>

app/views/spells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spells</h1>

  <% @spells.each do |spell| %>
    <h2><%= spell.name %></h2>
    <%= link_to 'Show', spell %>
    <%= link_to 'Edit', edit_spell_path(spell) %>
    <%= link_to 'Destroy', spell, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<br>
<%= link_to 'New Spell', new_spell_path %>

app/views/spells/new.html.erb
<div id="spell-body">

  <div id="scroll-spells">
    <%= image_tag "scroll.png", id: "spell-scroll", class: "img-responsive" %>
    <h1>Create a Spell</h1>

    <%= render 'form', spell: @spell %>

    <%= link_to 'Back', spells_path %>
  </div>

</div>

app/views/spells/show.html.erb
<h2><%= @spell.name %></h2>
<p><%= @spell.catagory %></p>
<p><%= @spell.description %></p>


<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_spell_path(@spell) %> |
<%= link_to 'Back', spells_path %>